Repository codestates-seb/seb39_main_010, pull requests merged in 2022-10, with the labels that each got.

#78 [FE] 로그인 버튼 컴포넌트, 로그인 모달 컴포넌트 추가
  client/src/assets/images/SocialLogos/google.svg
  client/src/assets/images/SocialLogos/index.ts
  client/src/assets/images/SocialLogos/kakao.svg
  client/src/assets/images/SocialLogos/naver.svg
  client/src/components/common/LoginModal/LoginModal.tsx
  client/src/components/common/SocialButtons/SocialButtons.tsx
  client/src/pages/Signup/Signup.tsx
Labels: ✨ feature, 📦 chore

#82 [FE] AuthInput 컴포넌트 코드 리팩토링 및 로그인 모달 내 기능 추가
  client/src/components/AuthInput/AuthInput.tsx
  client/src/components/common/BasicButton/BasicButton.tsx
  client/src/components/common/Header/Header.tsx
  client/src/components/common/LoginModal/LoginModal.tsx
Labels: ✨ feature, 🔨 refactor

#83 [FE] Question 페이지 추가
  client/src/assets/data/questionDummy.ts
  client/src/assets/images/avatar.svg
  client/src/components/pages/Question/Banner.tsx
  client/src/components/pages/Question/QuestionCard.tsx
  client/src/components/pages/Question/QuestionCards.tsx
  client/src/pages/Interveiw/Question/Question.tsx
Labels: ✨ feature, 📦 chore

#93 [FE] login, signup에 필요한 utils 및 api 함수 생성
  client/package-lock.json
  client/package.json
  client/src/apis/apiClient.ts
  client/src/utils/SignupValidation/index.ts
  client/src/utils/cookie/index.ts
Labels: ✨ feature, 📦 chore

#94 [FE] 글상세내용 컴포넌트 및 푸터 컴포넌트 추가
  client/src/assets/data/dummy.json
  client/src/components/common/Footer/Footer.tsx
  client/src/components/common/Input/SearchBox.tsx
  client/src/components/common/SelectBox/JobSelect.tsx
  client/src/components/common/SelectBox/JobSorting.tsx
  client/src/components/common/SelectBox/PopularSorting.tsx
  client/src/components/common/index.ts
  client/src/components/pages/Review/Accordion.tsx
  client/src/components/pages/Review/Reviews.tsx
  client/src/components/pages/Review/Write/Carrer.tsx
  client/src/components/pages/Review/Write/ContentsR.tsx
  client/src/components/pages/Study/Cards/Card/CardAll.tsx
  client/src/components/pages/Study/Cards/Card/CardDone.tsx
  client/src/components/pages/Study/Cards/Card/CardOn.tsx
  client/src/components/pages/Study/Cards/Card/style.ts
  client/src/components/pages/Study/Details/Comment.tsx
  client/src/components/pages/Study/Details/CommentIntro.tsx
  client/src/components/pages/Study/Details/Comments.tsx
  client/src/components/pages/Study/Details/Content.tsx
  client/src/components/pages/Study/Details/Title.tsx
  client/src/components/pages/Study/Write/ContentsS.tsx
  client/src/pages/Interveiw/Review/ReviewWrite.tsx
  client/src/pages/Study/StudyDetail.tsx
  client/src/routes/Router.tsx
Labels: ✨ feature, 💄 design

#102 [FE] signup, login 기능 추가
  client/src/apis/authApiClient.ts
  client/src/assets/data/questionDummy.ts
  client/src/assets/images/logo.svg
  client/src/components/common/Header/Header.tsx
  client/src/components/common/LoginModal/LoginModal.tsx
  client/src/components/pages/Question/QuestionCard.tsx
  client/src/components/pages/Question/QuestionCards.tsx
  client/src/pages/Interveiw/Question/Question.tsx
  client/src/pages/Interveiw/Question/QuestionDetail.tsx
  client/src/pages/Signup/Signup.tsx
  client/src/recoil/atom.ts
  client/src/types/index.ts
  client/src/utils/cookie/index.ts
  client/src/utils/signupValidation/index.ts
Labels: ✨ feature, 💄 design, 🔨 refactor, 📦 chore

#107 [FE] comment 관련 컴포넌트 폴더 이동 및 css 속성 변경
  client/src/components/common/Comments/Comment.tsx
  client/src/components/common/Comments/CommentIntro.tsx
  client/src/components/common/Comments/Comments.tsx
  client/src/pages/Study/StudyDetail.tsx
Labels: 💄 design, 🔧 etc

#124 [FE] 질문 작성 페이지 추가
  client/src/apis/apiClient.ts
  client/src/apis/authApiClient.ts
  client/src/pages/Interveiw/Question/QuestionWrite.tsx
  client/src/utils/apiUtilFunctions/index.ts
Labels: ✨ feature

#125 [FE] util 함수 추가 및 question 관련 페이지 api 연결
  client/src/apis/authApiClient.ts
  client/src/components/pages/Question/QuestionCard.tsx
  client/src/components/pages/Question/QuestionCards.tsx
  client/src/pages/Interveiw/index.tsx
  client/src/pages/Signup/Signup.tsx
  client/src/recoil/atom.ts
  client/src/routes/Router.tsx
  client/src/utils/cookie/index.ts
Labels: ✨ feature, 🔨 refactor

#131 [FE] merge to front
  client/package-lock.json
  client/package.json
  client/src/apis/apiClient.ts
  client/src/apis/authApiClient.ts
  client/src/assets/data/dummy.json
  client/src/assets/data/questionDummy.ts
  client/src/assets/images/SocialLogos/google.svg
  client/src/assets/images/SocialLogos/index.ts
  client/src/assets/images/SocialLogos/kakao.svg
  client/src/assets/images/SocialLogos/naver.svg
  client/src/assets/images/avatar.svg
  client/src/assets/images/logo.svg
  client/src/components/AuthInput/AuthInput.tsx
  client/src/components/common/BasicButton/BasicButton.tsx
  client/src/components/common/Comments/Comment.tsx
  client/src/components/common/Comments/CommentIntro.tsx
  client/src/components/common/Comments/Comments.tsx
  client/src/components/common/Footer/Footer.tsx
  client/src/components/common/Header/Header.tsx
  client/src/components/common/Input/Input.tsx
  client/src/components/common/Input/SearchBox.tsx
  client/src/components/common/LoginModal/LoginModal.tsx
  client/src/components/common/SelectBox/JobSelect.tsx
  client/src/components/common/SelectBox/JobSorting.tsx
  client/src/components/common/SelectBox/PopularSorting.tsx
  client/src/components/common/SocialButtons/SocialButtons.tsx
  client/src/components/common/index.ts
  client/src/components/pages/Question/Banner.tsx
  client/src/components/pages/Question/QuestionCard.tsx
  client/src/components/pages/Question/QuestionCards.tsx
  client/src/components/pages/Review/Accordion.tsx
  client/src/components/pages/Review/Reviews.tsx
  client/src/components/pages/Review/Write/Carrer.tsx
  client/src/components/pages/Review/Write/ContentsR.tsx
  client/src/components/pages/Study/Cards/Card/CardAll.tsx
  client/src/components/pages/Study/Cards/Card/CardDone.tsx
  client/src/components/pages/Study/Cards/Card/CardOn.tsx
  client/src/components/pages/Study/Cards/Card/style.ts
  client/src/components/pages/Study/Details/Content.tsx
  client/src/components/pages/Study/Details/Title.tsx
  client/src/components/pages/Study/Write/ContentsS.tsx
  client/src/index.tsx
  client/src/pages/Interveiw/Question/Question.tsx
  client/src/pages/Interveiw/Question/QuestionDetail.tsx
  client/src/pages/Interveiw/Question/QuestionWrite.tsx
  client/src/pages/Interveiw/Review/ReviewWrite.tsx
  client/src/pages/Interveiw/index.tsx
  client/src/pages/Signup/Signup.tsx
  client/src/pages/Study/StudyDetail.tsx
  client/src/recoil/atom.ts
  client/src/routes/Router.tsx
  client/src/types/index.ts
  client/src/utils/apiUtilFunctions/index.ts
  client/src/utils/cookie/index.ts
  client/src/utils/signupValidation/index.ts
Labels: ⚙️ infra
