Repository codestates-seb/seb39_main_010, pull requests merged in 2022-09, with the labels that each got.

#11 [FE] 스터디페이지 레이아웃 설정
  client/src/App.tsx
  client/src/components/common/Header/Header.tsx
  client/src/components/common/Header/style.ts
  client/src/components/common/Intro/Intro.tsx
  client/src/components/common/SearchBox/SearchBox.tsx
  client/src/components/common/Sorting/Sorting.tsx
  client/src/components/pages/Study/Category.tsx
  client/src/pages/Interveiw/Review/Review.tsx
  client/src/pages/Study/Study.tsx
  client/src/routes/Router.tsx
  client/src/styles/GlobalStyle.ts
Labels: 💄 design

#12 [FE] Review 상단 레이아웃 구현
  client/src/components/common/Filtering/Filtering.tsx
  client/src/components/common/Header/Header.tsx
  client/src/components/common/Intro/Intro.tsx
  client/src/components/common/JobSorting/JobSorting.tsx
  client/src/components/pages/Study/Category.tsx
  client/src/pages/Interveiw/Review/Review.tsx
  client/src/pages/Study/Study.tsx
Labels: ✨ feature, 💄 design

#27 [FE] Input, BasicButton component 생성
  client/src/components/common/BasicButton/BasicButton.tsx
  client/src/components/common/Input/Input.tsx
Labels: ✨ feature

#29 [FE] 스터디페이지 탭기능 구현
  client/src/assets/data/dummy.json
  client/src/components/common/Input/SearchBox.tsx
  client/src/components/common/SelectBox/SortingRectangle.tsx
  client/src/components/common/SelectBox/SortingRound.tsx
  client/src/components/common/Textarea/Textarea.tsx
  client/src/components/common/index.ts
  client/src/components/pages/Study/Card.tsx
  client/src/components/pages/Study/CardContent.tsx
  client/src/components/pages/Study/Cards/Card/CardAll.tsx
  client/src/components/pages/Study/Cards/Card/CardDone.tsx
  client/src/components/pages/Study/Cards/Card/CardOn.tsx
  client/src/components/pages/Study/Cards/Card/style.ts
  client/src/components/pages/Study/Cards/Content/CardContentAll.tsx
  client/src/components/pages/Study/Cards/Content/CardContentDone.tsx
  client/src/components/pages/Study/Cards/Content/CardContentOn.tsx
  client/src/components/pages/Study/Cards/index.ts
  client/src/components/pages/Study/Category.tsx
  client/src/components/pages/Study/SearchBar.tsx
  client/src/components/pages/Study/Write/Contents.tsx
  client/src/components/pages/index.ts
  client/src/pages/Interveiw/Review/Review.tsx
  client/src/pages/Study/Study.tsx
  client/src/pages/Study/StudyWrite.tsx
Labels: ✨ feature, 💄 design

#30 [FE] google font 적용
  client/public/index.html
  client/src/styles/GlobalStyle.ts
Labels: ✨ feature, 💄 design

#31 [FE] default theme color code 설정
  client/src/styles/styled.d.ts
  client/src/styles/theme.ts
Labels: 📦 chore

#32 [FE] 디자인 focus 추가
  client/src/components/common/Input/Input.tsx
  client/src/components/common/SelectBox/SortingRectangle.tsx
  client/src/components/common/Textarea/Textarea.tsx
  client/src/components/pages/Study/Write/Contents.tsx
Labels: 💄 design

#33 [FE] default theme color code 추가
  client/src/styles/styled.d.ts
  client/src/styles/theme.ts
Labels: 📦 chore

#47 [FE] Header width 변경
  client/src/components/common/Header/style.ts
Labels: 💄 design

#54 [FE] 마이페이지 컴포넌트 작성
  client/src/assets/data/dummy.json
  client/src/components/common/Header/Header.tsx
  client/src/components/common/Header/style.ts
  client/src/components/common/Intro/Intro.tsx
  client/src/components/common/SelectBox/JobSelect.tsx
  client/src/components/common/SelectBox/JobSorting.tsx
  client/src/components/common/SelectBox/PopularSorting.tsx
  client/src/components/common/Textarea/Textarea.tsx
  client/src/components/common/index.ts
  client/src/components/pages/Mypage/Introduction.tsx
  client/src/components/pages/Mypage/MyProfile.tsx
  client/src/components/pages/Mypage/Sorting/BoxCategoryL.tsx
  client/src/components/pages/Mypage/Sorting/BoxCategoryR.tsx
  client/src/components/pages/Mypage/Sorting/BoxCategoryW.tsx
  client/src/components/pages/Mypage/Sorting/NewPassword.tsx
  client/src/components/pages/Mypage/Sorting/SortingBoxL.tsx
  client/src/components/pages/Mypage/Sorting/SortingBoxR.tsx
  client/src/components/pages/Mypage/Sorting/SortingBoxW.tsx
  client/src/components/pages/Mypage/Sorting/index.ts
  client/src/components/pages/Mypage/Sorting/style.ts
  client/src/components/pages/Mypage/style.ts
  client/src/components/pages/Review/Write/Carrer.tsx
  client/src/components/pages/Review/Write/ContentsR.tsx
  client/src/components/pages/Study/Cards/Card/style.ts
  client/src/components/pages/Study/Cards/Content/CardContentAll.tsx
  client/src/components/pages/Study/Cards/Content/CardContentDone.tsx
  client/src/components/pages/Study/Cards/Content/CardContentOn.tsx
  client/src/components/pages/Study/Category.tsx
  client/src/components/pages/Study/SearchBar.tsx
  client/src/components/pages/Study/Write/ContentsS.tsx
  client/src/components/pages/Study/Write/Tag.tsx
  client/src/components/pages/index.ts
  client/src/pages/Interveiw/Review/Review.tsx
  client/src/pages/Interveiw/Review/ReviewWrite.tsx
  client/src/pages/Mypage/Mypage.tsx
  client/src/pages/Mypage/index.ts
  client/src/pages/Study/StudyWrite.tsx
  client/src/routes/Router.tsx
Labels: ✨ feature, 💄 design

#57 [FE] Textarea 컴포넌트 불필요한 코드 삭제
  client/src/components/common/Textarea/Textarea.tsx
Labels: 🔨 refactor

#58 [FE] Signup 페이지 추가
  client/src/components/common/Input/Input.tsx
  client/src/pages/Signup/Signup.tsx
Labels: ✨ feature, 💄 design

#59 [FE] Header import 위치 Router로 변경
  client/src/App.tsx
  client/src/routes/Router.tsx
Labels: 🔨 refactor
